### ISSUE TITLE
No module named "multi_layer_lstm.multi_layer_LSTM"

### ISSUE THREAD

**Issue by vinhqdang** [ML-on-structures/lstm-wikipedia#1]
Hello

Did I miss something else to run the script? 

I met this error while try to run ``python graph_analysis.py``

**Comment by rakshit-agrawal** [comment]
There was an unused import to a file in another repo that. I've fixed it. Please check

**Comment by vinhqdang** [comment]
It's working now :-) thanks for the quick fix. Anyway it's Vinh from email discussion.

**Comment by rakshit-agrawal** [comment]
Awesome :). Will update you on the other code pieces soon as well. They'll be added as a new branch in the same repo.

Closing the issue.
